#!/bin/bash

if [ -x "$JAVA_HOME/bin/java" ]; then
JAVA="$JAVA_HOME/bin/java"
else
JAVA=`which java`
fi

if [ ! -x "$JAVA" ]; then
echo "Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME"
exit 1
fi

if [ -x "`which mvn`" ]; then
MAVEN=`which java`
fi

if [ ! -x "$MAVEN" ]; then
echo "Could not MAVEN. Please install MAVEN"
exit 1
fi

start_build(){
mvn clean assembly:assembly
}

start_build
exit $?

