/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_JniNative */

#ifndef _Included_com_jni_JniNative
#define _Included_com_jni_JniNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_JniNative
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_JniNative_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
